### ISSUE TITLE
Unable to parse raw SIDC string

### ISSUE THREAD

**Issue by furoraest** [nwroyer/Python-Military-Symbols#4]
I tried to use examples given in README, to parse SIDC string into symbol, used the same line what is provided in example
```
# Create the same set of symbols as above, but by SIDC
military_symbol -o .  -n 10031000141211000000 10041000141211000000
```
----
Response:
```
More than one input; auto-naming anyway
        Unable to determine standard identity; assuming unknown
        WARNING: Unable to determine entity type from string "10031000141211000000"; defaulting to land unit
        Unable to determine standard identity; assuming unknown
        WARNING: Unable to determine entity type from string "10041000141211000000"; defaulting to land unit
```
And resulting generated file is: 10011000000000000000.svg

When i tried to use it via code, like
`military_symbol.get_symbol_and_svg_string("10031000141211000000",True)`
I get error response:
```
Traceback (most recent call last):
  File "C:\Source\milsym.py", line 8, in <module>
    val = military_symbol.get_symbol_and_svg_string("10031000141211000000",True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\military_symbol\command_line.py", line 128, in get_symbol_and_svg_string
    return symbol_cache.get_symbol_and_svg_string(creator_var, is_sidc, padding, style, use_variants, use_background=use_background, background_color=background_color)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\military_symbol\symbol_cache.py", line 94, in get_symbol_and_svg_string
    symbol: MilitarySymbol = cache_entry_tuple[0]
                             ~~~~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range
```
Please advice what is an issue here

**Comment by furoraest** [comment]
Seems like this is related to 1.0.7 version,
when using the latest from master (1.0.8) there are no issues
